# Generated by Django 3.1.1 on 2020-09-07 14:59

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('people', models.IntegerField()),
                ('QRcode', models.URLField()),
                ('QRimage', imagekit.models.fields.ProcessedImageField(upload_to='postings/resize/%Y%m%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visited_at', models.DateTimeField(auto_now=True)),
                ('out_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
